settings:
    data-dir: ~/my_data_dir
    recursive: true
    follow-links: false
    skip: ['.*']
templates:
    author:
        metadata:
            author: Huub de Beer
    today:
        preprocessors:
            -   preprocessors/today.rb
    webpage:
        glob: ['*.md']
        pandoc:
            to: html
            toc: true
            css:
                - assets/style.css
        postprocessors:
            - postprocessors/tidy.sh
    my-webpage:
        extends: ['author', 'today', 'webpage']
        pandoc:
            to: html5
            bibliography: 'assets/my-bibliography.bib'
