settings:
    data-dir: ~/my_data_dir
    recursive: true
    follow-links: false
    skip: ['.*']
templates:
    webpage:
        glob: ['*.md']
        pandoc:
            to: html
            toc: true
            css:
                - assets/style.css
        postprocessors:
            - postprocessors/tidy.sh
