templates:
    hello:
        pandoc:
            to: html
            css:
                - ./style.css
            template: hello-template.html
        postprocessors:
            - ./tidy.sh
    goodbye:
        extends: ['hello']
        pandoc:
            toc: true
            css:
                - ./goodbye-style.css
